/* Sparkle Bitch — scripts/fetch-fonts.cjs
 * Downloads the Latin subset of a curated set of open-licensed (OFL / Apache
 * 2.0) Y2K-flavoured fonts from Google Fonts and bundles them locally
 * (fonts/*.woff2 + fonts/fonts.css) so the app ships them with zero external
 * dependencies and works offline. Re-run to refresh or add fonts.
 *
 *   node scripts/fetch-fonts.cjs
 *
 * All fonts below are OFL or Apache 2.0 — redistribution (bundling) is allowed.
 */
'use strict';
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const OUT = path.join(__dirname, '..', 'fonts');

// family, weight, slug, css-generic-fallback
const FONTS = [
  // pixel / bitmap
  ['Press Start 2P', 400, 'pressstart2p', 'monospace'],
  ['Silkscreen', 400, 'silkscreen', 'monospace'],
  ['VT323', 400, 'vt323', 'monospace'],
  ['Pixelify Sans', 700, 'pixelifysans', 'sans-serif'],
  // techno / cyber
  ['Orbitron', 700, 'orbitron', 'sans-serif'],
  ['Michroma', 400, 'michroma', 'sans-serif'],
  ['Audiowide', 400, 'audiowide', 'sans-serif'],
  ['Zen Dots', 400, 'zendots', 'sans-serif'],
  ['Wallpoet', 400, 'wallpoet', 'sans-serif'],
  ['Syncopate', 700, 'syncopate', 'sans-serif'],
  // bubble / cute
  ['Baloo 2', 700, 'baloo2', 'sans-serif'],
  ['Fredoka', 600, 'fredoka', 'sans-serif'],
  ['Bungee', 400, 'bungee', 'sans-serif'],
  ['Chewy', 400, 'chewy', 'cursive'],
  ['Sniglet', 800, 'sniglet', 'sans-serif'],
  // retro display
  ['Monoton', 400, 'monoton', 'cursive'],
  ['Bungee Shade', 400, 'bungeeshade', 'sans-serif'],
  // blackletter / gothic
  ['UnifrakturCook', 700, 'unifrakturcook', 'serif'],
  ['Pirata One', 400, 'pirataone', 'serif'],
  // handwriting / grunge
  ['Permanent Marker', 400, 'permanentmarker', 'cursive'],
  ['Rock Salt', 400, 'rocksalt', 'cursive'],
  ['Shadows Into Light', 400, 'shadowsintolight', 'cursive'],
  ['Comic Neue', 700, 'comicneue', 'cursive']
];

function curl(url, binOut) {
  const base = `curl -sS -m 30 -A "${UA}"`;
  if (binOut) { execSync(`${base} "${url}" -o "${binOut}"`); return; }
  return execSync(`${base} "${url}"`, { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 });
}

// pull the Latin woff2 URL out of a css2 response
function latinWoff2(css) {
  const idx = css.indexOf('/* latin */');
  const scope = idx >= 0 ? css.slice(idx) : css;
  const m = scope.match(/https:\/\/[^)]+\.woff2/);
  if (m) return m[0];
  const all = css.match(/https:\/\/[^)]+\.woff2/g); // fallback: last url
  return all ? all[all.length - 1] : null;
}

if (!fs.existsSync(OUT)) fs.mkdirSync(OUT, { recursive: true });

const rules = [];
let ok = 0;
for (const [family, weight, slug, fallback] of FONTS) {
  try {
    const file = path.join(OUT, slug + '.woff2');
    // reuse an already-downloaded, valid file (so re-running only rebuilds CSS)
    let valid = fs.existsSync(file) && fs.statSync(file).size > 200 &&
      fs.readFileSync(file).slice(0, 4).toString('latin1') === 'wOF2';
    if (!valid) {
      const q = family.replace(/ /g, '+') + ':wght@' + weight;
      const css = curl(`https://fonts.googleapis.com/css2?family=${q}&display=swap`);
      const url = latinWoff2(css);
      if (!url) { console.error('  ✗ ' + family + ' (no woff2 url)'); continue; }
      curl(url, file);
      valid = fs.existsSync(file) && fs.statSync(file).size > 200 &&
        fs.readFileSync(file).slice(0, 4).toString('latin1') === 'wOF2';
    }
    if (!valid) { console.error('  ✗ ' + family + ' (bad file)'); continue; }
    // Weight RANGE so a Bold request never falls back off the bundled glyphs.
    rules.push(
      `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n  src: url('${slug}.woff2') format('woff2');\n}`
    );
    console.log('  ✓ ' + family + '  (' + fs.statSync(file).size + ' bytes)');
    ok++;
  } catch (e) {
    console.error('  ✗ ' + family + ' — ' + e.message.split('\n')[0]);
  }
}

const header = '/* Sparkle Bitch bundled fonts — generated by scripts/fetch-fonts.cjs.\n' +
  '   All families are OFL or Apache 2.0 licensed (redistribution allowed). */\n\n';
fs.writeFileSync(path.join(OUT, 'fonts.css'), header + rules.join('\n\n') + '\n');
console.log('\nbundled ' + ok + '/' + FONTS.length + ' fonts -> fonts/fonts.css');
